name: Build and Push Docker Image - Multiarch

on:
  push:
    branches: [ "main" ]
    paths: 
      - "./**"
      - ".github/workflows/actions-desafio9.yml"
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} # token dockerhub

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ${{ github.workspace }}./
        file: ${{ github.workspace }}./
        # Asume que tu Dockerfile está en la raíz de tu repositorio
        # Si tu Dockerfile está en una ruta específica, por ejemplo, ./path/to/Dockerfile, cambia 'context' y 'file' como sigue:
        # context: ./path/to/
        # file: ./path/to/Dockerfile
        push: true
        tags: pedrojonas/app-desafio9:${{ github.run_number }} # Cambia esto con tu nombre de usuario y nombre de imagen
        platforms: linux/amd64,linux/arm64,linux/arm/v7
    - name: Logout from DockerHub
      run: docker logout
